// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: asr_service.proto

package asrservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ASRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audio []byte `protobuf:"bytes,2,opt,name=audio,proto3" json:"audio,omitempty"`
}

func (x *ASRRequest) Reset() {
	*x = ASRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asr_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRRequest) ProtoMessage() {}

func (x *ASRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asr_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRRequest.ProtoReflect.Descriptor instead.
func (*ASRRequest) Descriptor() ([]byte, []int) {
	return file_asr_service_proto_rawDescGZIP(), []int{0}
}

func (x *ASRRequest) GetAudio() []byte {
	if x != nil {
		return x.Audio
	}
	return nil
}

type ASRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transcript string `protobuf:"bytes,2,opt,name=transcript,proto3" json:"transcript,omitempty"`
}

func (x *ASRResponse) Reset() {
	*x = ASRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asr_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRResponse) ProtoMessage() {}

func (x *ASRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asr_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRResponse.ProtoReflect.Descriptor instead.
func (*ASRResponse) Descriptor() ([]byte, []int) {
	return file_asr_service_proto_rawDescGZIP(), []int{1}
}

func (x *ASRResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

var File_asr_service_proto protoreflect.FileDescriptor

var file_asr_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x73, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x72, 0x22, 0x22, 0x0a, 0x0a, 0x41, 0x53, 0x52, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x2d, 0x0a, 0x0b,
	0x41, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x32, 0x78, 0x0a, 0x0a, 0x41,
	0x53, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x0f, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x12, 0x0f, 0x2e, 0x61,
	0x73, 0x72, 0x2e, 0x41, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x61, 0x73, 0x72, 0x2e, 0x41, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30,
	0x01, 0x12, 0x32, 0x0a, 0x0d, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69,
	0x7a, 0x65, 0x12, 0x0f, 0x2e, 0x61, 0x73, 0x72, 0x2e, 0x41, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x61, 0x73, 0x72, 0x2e, 0x41, 0x53, 0x52, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x61, 0x73, 0x72, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asr_service_proto_rawDescOnce sync.Once
	file_asr_service_proto_rawDescData = file_asr_service_proto_rawDesc
)

func file_asr_service_proto_rawDescGZIP() []byte {
	file_asr_service_proto_rawDescOnce.Do(func() {
		file_asr_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_asr_service_proto_rawDescData)
	})
	return file_asr_service_proto_rawDescData
}

var file_asr_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asr_service_proto_goTypes = []any{
	(*ASRRequest)(nil),  // 0: asr.ASRRequest
	(*ASRResponse)(nil), // 1: asr.ASRResponse
}
var file_asr_service_proto_depIdxs = []int32{
	0, // 0: asr.ASRService.StreamRecognize:input_type -> asr.ASRRequest
	0, // 1: asr.ASRService.SyncRecognize:input_type -> asr.ASRRequest
	1, // 2: asr.ASRService.StreamRecognize:output_type -> asr.ASRResponse
	1, // 3: asr.ASRService.SyncRecognize:output_type -> asr.ASRResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_asr_service_proto_init() }
func file_asr_service_proto_init() {
	if File_asr_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asr_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ASRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asr_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ASRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asr_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asr_service_proto_goTypes,
		DependencyIndexes: file_asr_service_proto_depIdxs,
		MessageInfos:      file_asr_service_proto_msgTypes,
	}.Build()
	File_asr_service_proto = out.File
	file_asr_service_proto_rawDesc = nil
	file_asr_service_proto_goTypes = nil
	file_asr_service_proto_depIdxs = nil
}
