// Code generated by goctl. DO NOT EDIT.
package types

type ASRRequest struct {
}

type ASRResponse struct {
	Transcript string `json:"transcript"`
}

type ChatMessage struct {
	UserId  string `json:"user_id"`
	Message string `json:"message"`
}

type ChatMessageRequest struct {
	UserId  string        `json:"user_id"`
	Message string        `json:"message"`
	History []ChatMessage `json:"history,optional"`
}

type ChatMessageResponse struct {
	Message string `json:"message"`
}

type LoginRequest struct {
	UserId string `json:"user_id" binding:"required"`
	Token  string `json:"token" binding:"required"`
}

type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type RAGChatMessageRequest struct {
	UserId    string `json:"user_id"`
	ContextId string `json:"context_id"`
	Message   string `json:"message"`
	Addition  string `json:"addition,optional"`
}

type RAGChatMessageResponse struct {
	Message string `json:"message"`
}

type RAGCreateContextRequest struct {
	UserId string `json:"user_id"`
}

type RAGCreateContextResponse struct {
	UserId    string `json:"user_id"`
	ContextId string `json:"context_id"`
}

type RAGCreateUserRequest struct {
	Username  string `json:"username"`
	Token     string `json:"token"`
	Interests string `json:"interests,optional"`
}

type RAGCreateUserResponse struct {
	UserId string `json:"user_id"`
}

type RAGFlushContextRequest struct {
	UserId    string `json:"user_id"`
	ContextId string `json:"context_id"`
}

type RAGFlushContextResponse struct {
	Status int32 `json:"status"`
}

type RecognitionRequest struct {
}

type RecognitionResponse struct {
	Items []RecognitionResponseItem `json:"items"`
	Count int32                     `json:"count"`
}

type RecognitionResponseItem struct {
	Name       string  `json:"name"`
	Confidence float32 `json:"confidence"`
}
