# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognition_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19recognition_service.proto\x12\x0brecognition"#\n\x12RecognitionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c";\n\x17RecognitionResponseItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02"Y\n\x13RecognitionResponse\x12\x33\n\x05items\x18\x01 \x03(\x0b\x32$.recognition.RecognitionResponseItem\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x32\x64\n\x12RecognitionService\x12N\n\tRecognize\x12\x1f.recognition.RecognitionRequest\x1a .recognition.RecognitionResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "recognition_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_RECOGNITIONREQUEST"]._serialized_start = 42
    _globals["_RECOGNITIONREQUEST"]._serialized_end = 77
    _globals["_RECOGNITIONRESPONSEITEM"]._serialized_start = 79
    _globals["_RECOGNITIONRESPONSEITEM"]._serialized_end = 138
    _globals["_RECOGNITIONRESPONSE"]._serialized_start = 140
    _globals["_RECOGNITIONRESPONSE"]._serialized_end = 229
    _globals["_RECOGNITIONSERVICE"]._serialized_start = 231
    _globals["_RECOGNITIONSERVICE"]._serialized_end = 331
# @@protoc_insertion_point(module_scope)
