# Rpc register key
Name: llm-service.rpc
ContainerName: llm-service
Host: 0.0.0.0
Port: 50051

OPENAI:
  API_KEY: "EMPTY"
  API_BASE: "http://localhost:8000/v1"
  MODEL: "Meta-Llama-3.1-8B-Instruct"

ETCD:
  Host: etcd
  Port: 2379