# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_service_pb2 as rag__service__pb2

GRPC_GENERATED_VERSION = "1.65.5"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.66.0"
SCHEDULED_RELEASE_DATE = "August 6, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in rag_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class RAGServiceStub(object):
    """Exporty RAG service for client"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
            "/rag.RAGService/StreamChat",
            request_serializer=rag__service__pb2.ChatMessageRequest.SerializeToString,
            response_deserializer=rag__service__pb2.ChatMessageResponse.FromString,
            _registered_method=True,
        )
        self.SyncChat = channel.unary_unary(
            "/rag.RAGService/SyncChat",
            request_serializer=rag__service__pb2.ChatMessageRequest.SerializeToString,
            response_deserializer=rag__service__pb2.ChatMessageResponse.FromString,
            _registered_method=True,
        )
        self.CreateUser = channel.unary_unary(
            "/rag.RAGService/CreateUser",
            request_serializer=rag__service__pb2.CreateUserRequest.SerializeToString,
            response_deserializer=rag__service__pb2.CreateUserResponse.FromString,
            _registered_method=True,
        )
        self.CheckUserValid = channel.unary_unary(
            "/rag.RAGService/CheckUserValid",
            request_serializer=rag__service__pb2.CheckUserRequest.SerializeToString,
            response_deserializer=rag__service__pb2.CheckUserResponse.FromString,
            _registered_method=True,
        )
        self.CreateChatContext = channel.unary_unary(
            "/rag.RAGService/CreateChatContext",
            request_serializer=rag__service__pb2.CreateContextRequest.SerializeToString,
            response_deserializer=rag__service__pb2.CreateContextResponse.FromString,
            _registered_method=True,
        )
        self.FlushChatHistory = channel.unary_unary(
            "/rag.RAGService/FlushChatHistory",
            request_serializer=rag__service__pb2.FlushContextRequest.SerializeToString,
            response_deserializer=rag__service__pb2.FlushContextResponse.FromString,
            _registered_method=True,
        )


class RAGServiceServicer(object):
    """Exporty RAG service for client"""

    def StreamChat(self, request, context):
        """Chat with stream response method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SyncChat(self, request, context):
        """Chat with sync response method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateUser(self, request, context):
        """Create new user"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckUserValid(self, request, context):
        """Check user valid"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateChatContext(self, request, context):
        """Create new chat context"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FlushChatHistory(self, request, context):
        """Flush chat history to database"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RAGServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamChat": grpc.unary_stream_rpc_method_handler(
            servicer.StreamChat,
            request_deserializer=rag__service__pb2.ChatMessageRequest.FromString,
            response_serializer=rag__service__pb2.ChatMessageResponse.SerializeToString,
        ),
        "SyncChat": grpc.unary_unary_rpc_method_handler(
            servicer.SyncChat,
            request_deserializer=rag__service__pb2.ChatMessageRequest.FromString,
            response_serializer=rag__service__pb2.ChatMessageResponse.SerializeToString,
        ),
        "CreateUser": grpc.unary_unary_rpc_method_handler(
            servicer.CreateUser,
            request_deserializer=rag__service__pb2.CreateUserRequest.FromString,
            response_serializer=rag__service__pb2.CreateUserResponse.SerializeToString,
        ),
        "CheckUserValid": grpc.unary_unary_rpc_method_handler(
            servicer.CheckUserValid,
            request_deserializer=rag__service__pb2.CheckUserRequest.FromString,
            response_serializer=rag__service__pb2.CheckUserResponse.SerializeToString,
        ),
        "CreateChatContext": grpc.unary_unary_rpc_method_handler(
            servicer.CreateChatContext,
            request_deserializer=rag__service__pb2.CreateContextRequest.FromString,
            response_serializer=rag__service__pb2.CreateContextResponse.SerializeToString,
        ),
        "FlushChatHistory": grpc.unary_unary_rpc_method_handler(
            servicer.FlushChatHistory,
            request_deserializer=rag__service__pb2.FlushContextRequest.FromString,
            response_serializer=rag__service__pb2.FlushContextResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "rag.RAGService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("rag.RAGService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class RAGService(object):
    """Exporty RAG service for client"""

    @staticmethod
    def StreamChat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/rag.RAGService/StreamChat",
            rag__service__pb2.ChatMessageRequest.SerializeToString,
            rag__service__pb2.ChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SyncChat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RAGService/SyncChat",
            rag__service__pb2.ChatMessageRequest.SerializeToString,
            rag__service__pb2.ChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateUser(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RAGService/CreateUser",
            rag__service__pb2.CreateUserRequest.SerializeToString,
            rag__service__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CheckUserValid(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RAGService/CheckUserValid",
            rag__service__pb2.CheckUserRequest.SerializeToString,
            rag__service__pb2.CheckUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateChatContext(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RAGService/CreateChatContext",
            rag__service__pb2.CreateContextRequest.SerializeToString,
            rag__service__pb2.CreateContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def FlushChatHistory(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/rag.RAGService/FlushChatHistory",
            rag__service__pb2.FlushContextRequest.SerializeToString,
            rag__service__pb2.FlushContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
