# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rag_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11rag_service.proto\x12\x03rag"\\\n\x12\x43hatMessageRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ncontext_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x10\n\x08\x61\x64\x64ition\x18\x04 \x01(\t"&\n\x13\x43hatMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t"\'\n\x14\x43reateContextRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t"<\n\x15\x43reateContextResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ncontext_id\x18\x02 \x01(\t":\n\x13\x46lushContextRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\ncontext_id\x18\x02 \x01(\t"&\n\x14\x46lushContextResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05"G\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x11\n\tinterests\x18\x03 \x01(\t"%\n\x12\x43reateUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t"2\n\x10\x43heckUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t""\n\x11\x43heckUserResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\xa3\x03\n\nRAGService\x12\x41\n\nStreamChat\x12\x17.rag.ChatMessageRequest\x1a\x18.rag.ChatMessageResponse0\x01\x12=\n\x08SyncChat\x12\x17.rag.ChatMessageRequest\x1a\x18.rag.ChatMessageResponse\x12=\n\nCreateUser\x12\x16.rag.CreateUserRequest\x1a\x17.rag.CreateUserResponse\x12?\n\x0e\x43heckUserValid\x12\x15.rag.CheckUserRequest\x1a\x16.rag.CheckUserResponse\x12J\n\x11\x43reateChatContext\x12\x19.rag.CreateContextRequest\x1a\x1a.rag.CreateContextResponse\x12G\n\x10\x46lushChatHistory\x12\x18.rag.FlushContextRequest\x1a\x19.rag.FlushContextResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "rag_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_CHATMESSAGEREQUEST"]._serialized_start = 26
    _globals["_CHATMESSAGEREQUEST"]._serialized_end = 118
    _globals["_CHATMESSAGERESPONSE"]._serialized_start = 120
    _globals["_CHATMESSAGERESPONSE"]._serialized_end = 158
    _globals["_CREATECONTEXTREQUEST"]._serialized_start = 160
    _globals["_CREATECONTEXTREQUEST"]._serialized_end = 199
    _globals["_CREATECONTEXTRESPONSE"]._serialized_start = 201
    _globals["_CREATECONTEXTRESPONSE"]._serialized_end = 261
    _globals["_FLUSHCONTEXTREQUEST"]._serialized_start = 263
    _globals["_FLUSHCONTEXTREQUEST"]._serialized_end = 321
    _globals["_FLUSHCONTEXTRESPONSE"]._serialized_start = 323
    _globals["_FLUSHCONTEXTRESPONSE"]._serialized_end = 361
    _globals["_CREATEUSERREQUEST"]._serialized_start = 363
    _globals["_CREATEUSERREQUEST"]._serialized_end = 434
    _globals["_CREATEUSERRESPONSE"]._serialized_start = 436
    _globals["_CREATEUSERRESPONSE"]._serialized_end = 473
    _globals["_CHECKUSERREQUEST"]._serialized_start = 475
    _globals["_CHECKUSERREQUEST"]._serialized_end = 525
    _globals["_CHECKUSERRESPONSE"]._serialized_start = 527
    _globals["_CHECKUSERRESPONSE"]._serialized_end = 561
    _globals["_RAGSERVICE"]._serialized_start = 564
    _globals["_RAGSERVICE"]._serialized_end = 983
# @@protoc_insertion_point(module_scope)
