# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x61sr_service.proto\x12\x03\x61sr"\x1b\n\nASRRequest\x12\r\n\x05\x61udio\x18\x02 \x01(\x0c"!\n\x0b\x41SRResponse\x12\x12\n\ntranscript\x18\x02 \x01(\t2x\n\nASRService\x12\x36\n\x0fStreamRecognize\x12\x0f.asr.ASRRequest\x1a\x10.asr.ASRResponse0\x01\x12\x32\n\rSyncRecognize\x12\x0f.asr.ASRRequest\x1a\x10.asr.ASRResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "asr_service_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ASRREQUEST"]._serialized_start = 26
    _globals["_ASRREQUEST"]._serialized_end = 53
    _globals["_ASRRESPONSE"]._serialized_start = 55
    _globals["_ASRRESPONSE"]._serialized_end = 88
    _globals["_ASRSERVICE"]._serialized_start = 90
    _globals["_ASRSERVICE"]._serialized_end = 210
# @@protoc_insertion_point(module_scope)
