# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import asr_service_pb2 as asr__service__pb2

GRPC_GENERATED_VERSION = "1.65.5"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.66.0"
SCHEDULED_RELEASE_DATE = "August 6, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in asr_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class ASRServiceStub(object):
    """Export asr service for client"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRecognize = channel.unary_stream(
            "/asr.ASRService/StreamRecognize",
            request_serializer=asr__service__pb2.ASRRequest.SerializeToString,
            response_deserializer=asr__service__pb2.ASRResponse.FromString,
            _registered_method=True,
        )
        self.SyncRecognize = channel.unary_unary(
            "/asr.ASRService/SyncRecognize",
            request_serializer=asr__service__pb2.ASRRequest.SerializeToString,
            response_deserializer=asr__service__pb2.ASRResponse.FromString,
            _registered_method=True,
        )


class ASRServiceServicer(object):
    """Export asr service for client"""

    def StreamRecognize(self, request, context):
        """ASR with stream response method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SyncRecognize(self, request, context):
        """ASR with sync response method"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ASRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamRecognize": grpc.unary_stream_rpc_method_handler(
            servicer.StreamRecognize,
            request_deserializer=asr__service__pb2.ASRRequest.FromString,
            response_serializer=asr__service__pb2.ASRResponse.SerializeToString,
        ),
        "SyncRecognize": grpc.unary_unary_rpc_method_handler(
            servicer.SyncRecognize,
            request_deserializer=asr__service__pb2.ASRRequest.FromString,
            response_serializer=asr__service__pb2.ASRResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "asr.ASRService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("asr.ASRService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class ASRService(object):
    """Export asr service for client"""

    @staticmethod
    def StreamRecognize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/asr.ASRService/StreamRecognize",
            asr__service__pb2.ASRRequest.SerializeToString,
            asr__service__pb2.ASRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SyncRecognize(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/asr.ASRService/SyncRecognize",
            asr__service__pb2.ASRRequest.SerializeToString,
            asr__service__pb2.ASRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
